services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: askme_test
    ports:
      - "5433:5432"

  wiremock:
    image: wiremock/wiremock:3.3.1
    ports:
      - "8080:8080"
    volumes:
      - ./tests/mock/wiremock:/home/wiremock
    command:
      - --global-response-templating
      - --enable-stub-cors
